export default class PropertyTaxTransactionModel {
  constructor(
    public id?: string,
    public cMonthInterest?: number,
    public cPayable?: number,
    public cTotalBalance?: number,
    public cTotalInterest?: number,
    public cTotalTax?: number,
    public createdAt?: Date,
    public createdBy?: string,
    public cycle?: number,
    public districtId?: string,
    public districtName?: string,
    public extra?: number,
    public lastPaidAt?: Date,
    public maxTax?: number,
    public minTax?: number,
    public paidAmount?: number,
    public paidDate?: Date,
    public paidLocation?: string,
    public paidMode?: string,
    public panchayatId?: string,
    public panchayatName?: string,
    public payerEmail?: string,
    public payerId?: string,
    public payerMobile?: string,
    public payerName?: string,
    public prevBalance?: number,
    public prevInterest?: number,
    public propertyId?: string,
    public propertyType?: string,
    public stateId?: string,
    public stateName?: string,
    public talukId?: string,
    public talukName?: string,
    public taxYear?: number,
    public totalPaid?: number,
    public workLog?: string,
    public education?: string,
    public electricity?: string,
    public financialYear?: string,
    public health?: string,
    public library?: string,
    public specialWater?: string,
    public beggary?: string,
    public water?: string
  ) {}
}

// public prevTotal?: number,
